version: '3'

services:
    nginx:
        image: 098106984154.dkr.ecr.us-west-2.amazonaws.com/nginx-ecs-simple
        container_name: nginx
        networks:
            - thenet
        ports:
            - '80:80'
        # volumes:
        #     - ./nginx.conf:/etc/nginx/nginx.conf
        logging:
            driver: awslogs
            options: 
                awslogs-group: simple-stack-nginx
                awslogs-region: us-west-2
                awslogs-stream-prefix: nginx
    app:
        image: 098106984154.dkr.ecr.us-west-2.amazonaws.com/app
        container_name: app
        networks:
            - thenet
        logging:
            driver: awslogs
            options: 
                awslogs-group: simple-stack-app
                awslogs-region: us-west-2
                awslogs-stream-prefix: app

networks:
    thenet: