version: '3'

services:
    nginx:
        image: 098106984154.dkr.ecr.us-west-2.amazonaws.com/nginx-ecs-service-discovery
        container_name: nginx
        ports:
            - '80:80'
        logging:
            driver: awslogs
            options: 
                awslogs-group: simple-stack-app
                awslogs-region: us-west-2
                awslogs-stream-prefix: nginx