version: '3'

services:
    app:
        image: 098106984154.dkr.ecr.us-west-2.amazonaws.com/app
        container_name: app
        ports:
            - '3000:3000'
        logging:
            driver: awslogs
            options: 
                awslogs-group: simple-stack-app
                awslogs-region: us-west-2
                awslogs-stream-prefix: app
